/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author w
 */
import java.sql.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
public class login_page extends javax.swing.JFrame {
static Connection c;
    static Statement ss;
    static String query;
    /**
     * Creates new form login_page
     */
    public login_page() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        us = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("PROJECT MANAGEMENT  SYSTEM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(75, 6, 410, 64);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("USER NAME :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 170, 86, 20);
        getContentPane().add(us);
        us.setBounds(210, 170, 160, 30);
        getContentPane().add(pass);
        pass.setBounds(210, 230, 160, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("PASSWORD :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 230, 85, 20);

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1.setText("LOGIN ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 290, 90, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginNN.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, -50, 730, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        sec s1= new sec();
        try{
            c=s1.connect();
            ss=c.createStatement();
//         String id="null";
         String username=us.getText();
        String pasw = pass.getText();
         String salary="null";
          String pos="null";
        String query = "insert into users values('" + username + "','" + pasw + "','" + salary+ "','" + pos+ "')";
        ss.executeUpdate(query);
//        if(username.equals("projectmanager")&&pasw.equals("projectmanager")){
//        project_mangerer obj=new project_mangerer();
//        obj.setVisible(true);
//       dispose();
//        
//        }
//        else{
//         JOptionPane.showMessageDialog(this,"Invalid user name or password! Try again");
//         us.setText("");
//        pass.setText("");
//        }
            
       
            ss.execute(query);
            System.out.println("Done");
        }
        catch(SQLException ex){
            System.out.println("Error");
            System.out.println(ex.getMessage());
        }
        finally{
            try{
                c.close();
                ss.close();
            }catch(SQLException ex)
            {
                System.out.println(ex.getMessage());
            }
            
            
        }
        String username=us.getText();
        String pasw = pass.getText();
    if(username.equals("projectmanager")&&pasw.equals("projectmanager")){
        project_mangerer obj=new project_mangerer();
        obj.setVisible(true);
       dispose();
        
        }
    else if(username.equals("teamleader")&&pasw.equals("teamleader")){
    TEAMLEADERs tm=new   TEAMLEADERs();
        tm.setVisible(true);
       dispose();
    }
    else if(username.equals("employee")&&pasw.equals("employee")){
    NewJFrame tm=new NewJFrame();
        tm.setVisible(true);
       dispose();
    }
    else if(username.equals("admin")&&pasw.equals("admin")){
    admin1 ad=new admin1();
        ad.setVisible(true);
       dispose();
    }
        else{
         JOptionPane.showMessageDialog(this,"Invalid user name or password! Try again");
         us.setText("");
        pass.setText("");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField us;
    // End of variables declaration//GEN-END:variables
}
