//package project_manager;


//import java.sql.*;
//import java.util.*;
//import javax.swing.table.DefaultTableModel;
//import java.util.Scanner;
import java.sql.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import java.util.Scanner;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author IT
 */
public class TEAMLEADERs extends javax.swing.JFrame {
    static Connection c;
    static Statement ss;
    static String query;


    /**
     * Creates new form TEAMLEADERs
     */
    public TEAMLEADERs() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        penlaties = new javax.swing.JButton();
        assigntask = new javax.swing.JButton();
        completetask = new javax.swing.JButton();
        assignedproject = new javax.swing.JButton();
        projectprograss = new javax.swing.JButton();
        reports = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        vac = new javax.swing.JButton();

        jButton7.setText("jButton7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Team Leader");
        jLabel1.setToolTipText("");

        penlaties.setBackground(new java.awt.Color(0, 153, 153));
        penlaties.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        penlaties.setText("penlaties");
        penlaties.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penlatiesActionPerformed(evt);
            }
        });

        assigntask.setBackground(new java.awt.Color(0, 153, 153));
        assigntask.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        assigntask.setText("assign tasks");
        assigntask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assigntaskActionPerformed(evt);
            }
        });

        completetask.setBackground(new java.awt.Color(0, 153, 153));
        completetask.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        completetask.setText("complete tasks");
        completetask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completetaskActionPerformed(evt);
            }
        });

        assignedproject.setBackground(new java.awt.Color(0, 153, 153));
        assignedproject.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        assignedproject.setText("assigned projects");
        assignedproject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignedprojectActionPerformed(evt);
            }
        });

        projectprograss.setBackground(new java.awt.Color(0, 153, 153));
        projectprograss.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        projectprograss.setText("project prograss");
        projectprograss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectprograssActionPerformed(evt);
            }
        });

        reports.setBackground(new java.awt.Color(0, 153, 153));
        reports.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reports.setText("reports");
        reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 153, 153));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back-icon (1).png"))); // NOI18N
        jButton9.setText("Back");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Premium Vector _ People are working in offices illustration.jpg"))); // NOI18N

        vac.setBackground(new java.awt.Color(0, 153, 153));
        vac.setText("vacation");
        vac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(assignedproject, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reports, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(projectprograss, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(completetask, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(assigntask, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(penlaties, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addGap(18, 18, 18))))
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(vac)
                        .addGap(32, 32, 32)
                        .addComponent(penlaties)
                        .addGap(41, 41, 41)
                        .addComponent(assigntask)
                        .addGap(44, 44, 44)
                        .addComponent(completetask)
                        .addGap(40, 40, 40)
                        .addComponent(assignedproject)
                        .addGap(39, 39, 39)
                        .addComponent(projectprograss)
                        .addGap(32, 32, 32)
                        .addComponent(reports)))
                .addGap(37, 37, 37)
                .addComponent(jButton9)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void penlatiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penlatiesActionPerformed
        // TODO add your handling code here:
        Teamleaderpenalties pi2=new Teamleaderpenalties();
        pi2.setVisible(true);
        dispose();
    }//GEN-LAST:event_penlatiesActionPerformed

    private void assigntaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assigntaskActionPerformed
tmassigntask pi3=new tmassigntask();
        pi3.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_assigntaskActionPerformed

    private void completetaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completetaskActionPerformed
        // TODO add your handling code here:
        completetask pi3=new completetask();
        pi3.setVisible(true);
        dispose();
    }//GEN-LAST:event_completetaskActionPerformed

    private void assignedprojectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignedprojectActionPerformed
        // TODO add your handling code here:
        assignedproj pi6=new assignedproj();
        pi6.setVisible(true);
        dispose();
    }//GEN-LAST:event_assignedprojectActionPerformed

    private void projectprograssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectprograssActionPerformed
        // TODO add your handling code here:
        tmprojectprog pi4=new tmprojectprog();
        pi4.setVisible(true);
        dispose();
    }//GEN-LAST:event_projectprograssActionPerformed

    private void reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsActionPerformed
        // TODO add your handling code here:
        tmreports pi5=new tmreports();
        pi5.setVisible(true);
        dispose();
    }//GEN-LAST:event_reportsActionPerformed

    private void vacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vacActionPerformed
        // TODO add your handling code here:
        TEAMLeaderVAc n1= new TEAMLeaderVAc();
n1.show();
dispose();
    }//GEN-LAST:event_vacActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TEAMLEADERs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TEAMLEADERs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TEAMLEADERs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TEAMLEADERs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TEAMLEADERs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignedproject;
    private javax.swing.JButton assigntask;
    private javax.swing.JButton completetask;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton penlaties;
    private javax.swing.JButton projectprograss;
    private javax.swing.JButton reports;
    private javax.swing.JButton vac;
    // End of variables declaration//GEN-END:variables
}
